# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 07:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_follows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follows',
            name='follows',
            field=models.ManyToManyField(default=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL), related_name='followed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
