# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsys', '0003_auto_20161115_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='/home/user/task/media/image', verbose_name='image'),
        ),
    ]
