# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsys', '0006_auto_20161116_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar/avatar.png', null=True, upload_to='image/', verbose_name='image'),
        ),
    ]
